# Author: kk.Fang(fkfkbill@gmail.com)


# 规则代码的调用入口

ALL_RULE_ENTRIES = (
    # SQL语句类型相关
    RULE_ENTRY_DDL := "DDL",
    RULE_ENTRY_DML := "DML",

    # 工单相关
    RULE_ENTRY_TICKET := "TICKET",
    RULE_ENTRY_TICKET_STATIC := "TICKET_STATIC",
    RULE_ENTRY_TICKET_STATIC_CMDB_INDEPENDENT := "TICKET_STATIC_CMDB_INDEPENDENT",
    RULE_ENTRY_TICKET_DYNAMIC := "TICKET_DYNAMIC",

    # 线上审核相关
    RULE_ENTRY_ONLINE := "ONLINE"
)


# 规则优先级

ALL_RULE_LEVELS = (
    RULE_LEVEL_INFO := 1,
    RULE_LEVEL_WARNING := 2,
    RULE_LEVEL_SEVERE := 3
)

RULE_LEVELS_CHINESE = {
    RULE_LEVEL_INFO: "提示",
    RULE_LEVEL_WARNING: "警告",
    RULE_LEVEL_SEVERE: "严重"
}


# 规则输入输出的对象类型校验

ALL_RULE_PARAM_TYPES = (
    RULE_PARAM_TYPE_STR := "STR",
    RULE_PARAM_TYPE_INT := "INT",
    RULE_PARAM_TYPE_FLOAT := "FLOAT",
    RULE_PARAM_TYPE_NUM := "NUM",
    RULE_PARAM_TYPE_LIST := "LIST"
)
