# Author: kk.Fang(fkfkbill@gmail.com)


# 规则代码的调用入口

RULE_ENTRY_DDL = "DDL"
RULE_ENTRY_DML = "DML"

RULE_ENTRY_TICKET = "TICKET"
RULE_ENTRY_TICKET_STATIC = "TICKET_STATIC"
RULE_ENTRY_TICKET_DYNAMIC = "TICKET_DYNAMIC"

RULE_ENTRY_ONLINE = "ONLINE"

ALL_RULE_ENTRIES = (
    RULE_ENTRY_DDL,
    RULE_ENTRY_DML,
    RULE_ENTRY_TICKET,
    RULE_ENTRY_TICKET_STATIC,
    RULE_ENTRY_TICKET_DYNAMIC,
    RULE_ENTRY_ONLINE
)
