# Author: kk.Fang(fkfkbill@gmail.com)

# 时间格式

COMMON_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss'
COMMON_DATE_FORMAT = 'YYYY-MM-DD'
COMMON_DATE_FORMAT_COMPACT = 'YYYYMMDD'
COMMON_TIME_FORMAT = 'HH:mm:ss'


# OBJ规则的子类型（obj_info_type）

# OBJ_RULE_TYPE_TABLE = "TABLE"
# OBJ_RULE_TYPE_PART_TABLE = "PART_TABLE"
# OBJ_RULE_TYPE_INDEX = "INDEX"
# OBJ_RULE_TYPE_VIEW = "VIEW"
# OBJ_RULE_TYPE_SEQ = "SEQUENCE"
# ALL_OBJ_RULE_TYPE = (OBJ_RULE_TYPE_TABLE, OBJ_RULE_TYPE_PART_TABLE, OBJ_RULE_TYPE_INDEX,
#                      OBJ_RULE_TYPE_VIEW, OBJ_RULE_TYPE_SEQ)

# 仪表盘以及概览页所需的统计数据

# STATS_NUM_SQL_TEXT = RULE_TYPE_TEXT
# STATS_NUM_SQL_PLAN = RULE_TYPE_SQLPLAN
# STATS_NUM_SQL_STATS = RULE_TYPE_SQLSTAT
# STATS_NUM_SQL = "SQL"  # 这一条包括了上面的三种的和
# STATS_NUM_TAB = OBJ_RULE_TYPE_TABLE
# STATS_NUM_INDEX = OBJ_RULE_TYPE_INDEX
# STATS_NUM_SEQUENCE = OBJ_RULE_TYPE_SEQ
# STATS_NUM_OBJ = RULE_TYPE_OBJ
# ALL_STATS_NUM_TYPE = (
#     STATS_NUM_SQL_TEXT,
#     STATS_NUM_SQL_PLAN,
#     STATS_NUM_SQL_STATS,
#     STATS_NUM_SQL,
#     STATS_NUM_TAB,
#     STATS_NUM_INDEX,
#     STATS_NUM_SEQUENCE,
#     STATS_NUM_OBJ
# )


# 评分显示类型

SCORE_BY_AVERAGE = 1  # 按照平均分展示
SCORE_BY_LOWEST = 2  # 按照最低分展示
ALL_SCORE_BY = (SCORE_BY_AVERAGE, SCORE_BY_LOWEST)


